In [2]:
import  numpy as np

In [3]:
array= np.array([140,166,174,192])

In [4]:
array/2.2

array([63.63636364, 75.45454545, 79.09090909, 87.27272727])

In [5]:
ones=np.ones((3,4))

In [6]:
ones.reshape((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
array.flatten()

array([140, 166, 174, 192])

In [8]:
ones.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])