In [2]:
import numpy as np


In [6]:
array=np.array([1,2,3,4,5])
array.shape

(5,)

In [4]:
np.random.rand(2,1)

array([[0.67299458],
       [0.85418894]])

In [7]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.arange(3,27,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [12]:
np.arange(27,3,-3)

array([27, 24, 21, 18, 15, 12,  9,  6])