In [1]:
import numpy as np

In [2]:
array= np.ones((4,))
array.shape

(4,)

### Expanded New Row

In [8]:
expanded_array=array[np.newaxis,:]
expanded_array.shape

(1, 4)

In [9]:
expanded_array

array([[1., 1., 1., 1.]])

In [5]:
array

array([1., 1., 1., 1.])

### Conditional New Array


In [10]:
array=np.array([[13,15,30],[45,22,11],[56,15,22]])
array>20

array([[False, False,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [11]:
array[array<20]

array([13, 15, 11, 15])

### Slicing

In [12]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [13]:
a[1:4]

array([1, 2, 3])

### Stacking

In [14]:
first= np.full((2,12),2)
second=np.full((2,7),2)
np.hstack((first,second))

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [17]:
first= np.full((1,7),1)
second=np.full((2,7),2)
np.vstack((first,second))

array([[1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

### Splitting Arras

In [20]:
a= np.arange(1,11)
np.hsplit(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [21]:
first,second=np.hsplit(a,2)

In [22]:
first

array([1, 2, 3, 4, 5])

In [23]:
second

array([ 6,  7,  8,  9, 10])